### ISSUE TITLE
Firefox sign-in callback issue

### ISSUE THREAD

**Issue by sainiroop** [imodeljs/imodeljs-samples#12]
I recently deployed an interactive app from the samples repo. 
My deployment worked fine in chrome, but firefox was getting stuck in the sign-in callback step:

![image](https://user-images.githubusercontent.com/6562563/72624155-0a18a700-390c-11ea-9db8-63bd809d9605.png)

This is because [signin-callback.html](https://github.com/imodeljs/imodeljs-samples/blob/master/interactive-app/simple-viewer-app/public/signin-callback.html) uses a link rel=”import” that’s not supported in Firefox.

The workaround is the replace the contents of the signin-callback.html with the following:

```
  <script type="text/javascript" src="v0.0.0/runtime.js"></script>
  <script type="text/javascript" src="v1.9.0/IModelJsLoader.js" data-imjsversions='{"main":"0.0.0","bentleyjs-core":"1.9.0","geometry-core":"1.9.0","imodeljs-clients":"1.9.0","imodeljs-common":"1.9.0","imodeljs-frontend":"1.9.0","imodeljs-i18n":"1.9.0","imodeljs-quantity":"1.9.0","ui-components":"1.9.0","ui-abstract":"1.9.0","ui-core":"1.9.0","presentation-components":"1.9.0","presentation-frontend":"1.9.0","presentation-common":"1.9.0","inspire-tree":"5.0.2","lodash":"4.17.15","react":"16.12.0","react-dnd":"5.0.0","react-dnd-html5-backend":"5.0.1","react-dom":"16.12.0","react-redux":"5.1.2","redux":"4.0.4"}'></script>
```

A permanent fix is still in the works.

**Comment by calebmshafer** [comment]
With the release of iModel.js 2.0, this is no longer an issue with firefox and deploying the sample applications.
