### ISSUE TITLE
simple-viewer-app error ： Property imjs_test_project does not exist?

### ISSUE THREAD

**Issue by muhuashanjin** [imodeljs/imodeljs-samples#7]
![image](https://user-images.githubusercontent.com/18102472/68823833-f5335380-06cf-11ea-8a7e-915bc43ddb3b.png)
![image](https://user-images.githubusercontent.com/18102472/68823858-041a0600-06d0-11ea-9164-a1a30757af78.png)
![image](https://user-images.githubusercontent.com/18102472/68823887-13994f00-06d0-11ea-8c3f-e15b9d3d97ef.png)
![image](https://user-images.githubusercontent.com/18102472/68823973-50fddc80-06d0-11ea-84c5-f1590bddd458.png)
![image](https://user-images.githubusercontent.com/18102472/68823986-5824ea80-06d0-11ea-9592-518e540d6a1f.png)

**Comment by ColinKerr** [comment]
Did you rebuild after you set the 'imjs_test_project' variable?  If not do:

```
rush build --to simple-viewer-app 
```
This will rebuild just the simple viewer app.  If you do this and it still does not work try cleaning then rebuilding by calling:
```
npm run clean
rush build --to simple-viewer-app
```
The npm command must be run from the simple-viewer-app directory.  The clean command will remove the lib folder from simple-viewer-app and ensure the rebuild is starting from scratch.

**Comment by aderderian** [comment]
See my issue here as well : https://github.com/imodeljs/imodeljs-samples/issues/8
