### ISSUE TITLE
iModelHub Name for iModel is incorrect

### ISSUE THREAD

**Issue by aderderian** [imodeljs/imodeljs-samples#8]
For some reason I need to name my iModel the original name of my project in order for it to work. The project gets renamed to a random string. The Bentley iModel Hub shows the wrong name for the iModel. Naming is inconsistent throughout Projectwise as well.

   "imjs_test_project" : "Test Project - 127839040", // Set this to the name of the sample project
   "imjs_test_imodel"  : "Test Project" // Set this to the name of the sample iModel

![image](https://user-images.githubusercontent.com/868165/68979245-057c2900-07cb-11ea-8155-5414dfa725ce.png)

**Comment by williamkbentley** [comment]
I am having trouble reproducing this. The random numbers are appended to the project and imodel names to ensure unique project names. Did you attempt to rename the iModel or project after creation?

**Comment by aderderian** [comment]
Hello, 

Thanks for responding. What I think has happened here is that maybe Test Project exists in the iModel universe even outside of my specific application and account. This seems strange to me that it would need to make this project name unique since it was the only project I have. Secondarily, what happened was it displays the iModelName in the Portal as "Test Project - 127839040", but as I show in my iModel.j configuration it wants "Test Project" as the iModel name. Almost as if the name I entered is still being honored in a different db than the one the portal looks at. I assume you tried with the project specifically named "Test Project"? Thx for your help.

**Comment by calebmshafer** [comment]
@aderderian we have identified the issue and are working on a fix now.  We'll an update once a fix is in place

**Comment by aderderian** [comment]
@calebmshafer great to hear! I am glad you were able to repro. That's the hardest part. :)

**Comment by williamkbentley** [comment]
This issue has been fixed going forward.

@aderderian You can click the "Edit Project" button and change the name of your iModel to what the Bentley iModel Hub shows. This will get the Getting Started dashboard and iModel Hub on the same page for your project.
