### ISSUE TITLE
Unable to use the project on Mac OSX

### ISSUE THREAD

**Issue by yesprasoon** [imodeljs/imodeljs-samples#9]
Is it not possible to use web app samples on Mac OS?
On "npm i" it comes up with Platform error.

**Comment by calebmshafer** [comment]
We currently do not publish a MacOS version of the iModel.js native node addon so the samples will not work on a Mac.  

The list of currently supported platforms can be found here: https://imodeljs.org/learning/supportedplatforms/.

We're working on getting one published and will update that list once it's available.

**Comment by calebmshafer** [comment]
@yesprasoon MacOS is now officially supported as of iModel.js 1.12.0.  Let us know if you face any issues when using it.  Thanks!

**Comment by yesprasoon** [comment]
I tried with three projects and here are the issues in those 3 when I try
to do npm i or npm install:

*viewer-only-sample* = GET
https://registry.npmjs.org/@bentley/frontend-sample-base - Not found

*query-agent* = GET https://registry.npmjs.org/imodel-changeset-test-utility
- Not found

*simple-viewer-app* = Unsupported platform for simple-viewer-app@0.0.0:
wanted {"os":"win32,linux","arch":"any"} (current:
{"os":"darwin","arch":"x64"})

**Comment by calebmshafer** [comment]
@yesprasoon the imodeljs-samples repo and all of the samples within it are setup using Rush so you'll need to use that to install the samples.  [Here](https://github.com/imodeljs/imodeljs-samples#building-samples) are the steps from the README for how to builds the samples.

In terms of the `Unsupported platform for simple-viewer-app@0.0.0:...`, that's a bug on our part.  We'll have a fix available soon.
